version: '3.7'
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: ${CONTEXT_NAME}_verdaccio
    environment:
      - NODE_ENV=production
      - VERDACCIO_PORT=4873
    volumes:
      - "$CONTEXT_DIR/data-verdaccio/storage:/verdaccio/storage"
      # - "$CONTEXT_DIR/data-verdaccio/config:/verdaccio/conf"
      - "$CONTEXT_DIR/data-verdaccio/plugins:/verdaccio/plugins" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verdaccio.entrypoints=web"
      - "traefik.http.routers.verdaccio.rule=Host(`$VERDACCIO_HOST`)"
      - "traefik.http.services.verdaccio.loadbalancer.server.port=4873"
    networks:
      - internal-network
