version: '3.7'
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  gitea:
    image: gitea/gitea:latest
    container_name: ${CONTEXT_NAME}_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=${GITEA_URL}
      - SSH_DOMAIN=${GITEA_HOST}
      - HTTP_PORT=80
    ports:
      - "$GITEA_SSH_PORT:22"
    volumes:
      - "$CONTEXT_DIR/data-gitea:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.rule=Host(`$GITEA_HOST`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=80"
    networks:
      - internal-network
