version: "2"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://192.168.1.145:3000
      - SSH_DOMAIN=mydomain.com
      - HTTP_PORT=3000
    restart: always
    volumes:
      - /data/dockerApp/gitea:/data
    ports:
      - "3000:3000"
      - "10022:22"
    networks:
      - cinet
      - proxy

  drone-server:
    image: drone/drone:latest
    container_name: drone-server
    ports:
      - 8080:80
      - 9000
    volumes:
      - /data/dockerApp/drone:/var/lib/drone/
    restart: always
    depends_on:
      - gitea
    environment:
      - DRONE_OPEN=true
        #- DRONE_DEBUG=true
        #- DRONE_LOGS_DEBUG=true
        #- DRONE_LOGS_TEXT=true
        #- DRONE_LOGS_TRACE=true
      - DRONE_SERVER_PORT=:80
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://192.168.1.145:3000
      - DRONE_RPC_SECRET=9c3920e3e748aff735d2e16ef31fbc12
      - DRONE_SERVER_HOST=192.168.1.145:8080
      - DRONE_HOST=http://192.168.1.145:8080
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_NETWORK=cinet
      - DRONE_GITEA_CLIENT_ID=c13f099b-1b66-12cb-ba2a-4bec804ad113
      - DRONE_GITEA_CLIENT_SECRET=N3CzDcWnxC12LMYmyDwKzbixkkTXbJJE1Lss5BOQc9w= 
    networks:
      - cinet

  drone-agent:
    image: drone/agent:latest
    container_name: drone-agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://192.168.1.145:8080
      - DRONE_RPC_SECRET=9c3920e3e748aff735d2e16ef31fbc12
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_NETWORK=cinet
      - DRONE_RUNNER_NETWORKS=cinet
    networks:
      - cinet


networks:
  cinet:
    external: true
  proxy:
    external: true
