version: '3.7'
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  nginx-proxy:
    container_name: ${CONTEXT_NAME}_nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $CONTEXT_DIR/data-nginx-proxy/certs:/etc/nginx/certs
      - $CONTEXT_DIR/data-nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - $CONTEXT_DIR/data-nginx-proxy/html:/usr/share/nginx/html
    networks:
      - internal-network