version: "3.3"
networks:
  internal-network:
    name: ${CONTEXT_NAME}_network
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=$TRAEFIK_DEBUG"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
    #  - "--entrypoints.traefik.address=:8282" #dashboard default port 8080
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
 #     - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
 #     - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
 #     - "--certificatesresolvers.myresolver.acme.email=hello@paularah.com"
 #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
      - "$TRAEFIK_DASHBOARD_PORT:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - internal-network


